/**
 * 本地静态应用目录
 * 来源：app_catalog 表（36 条，已验证有安装包）
 * 优先级：本地数据优先，可随时从 Supabase 增量刷新
 */
import type { AppItem } from '@/types';

export const LOCAL_CATALOG: AppItem[] = [
  { id: 114809729, full_name: 'microsoft/vscode', name: 'Visual Studio Code', description: 'Visual Studio Code - Open Source', owner: 'microsoft', repo: 'vscode', avatar_url: 'https://avatars.githubusercontent.com/u/6154722', stars: 165000, forks: 29000, language: 'TypeScript', topics: ['electron', 'editor', 'typescript'], platforms: ['Windows', 'macOS', 'Linux'], latest_version: '1.94.2', latest_release_date: null, html_url: 'https://github.com/microsoft/vscode', updated_at: '2024-10-01T00:00:00+00:00', license: 'MIT', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 55000003, full_name: 'microsoft/PowerToys', name: 'PowerToys', description: 'Windows system utilities to maximize productivity', owner: 'microsoft', repo: 'PowerToys', avatar_url: 'https://avatars.githubusercontent.com/u/6154722', stars: 111000, forks: 6500, language: 'C#', topics: ['windows', 'productivity', 'system-tools'], platforms: ['Windows'], latest_version: 'v0.85.0', latest_release_date: null, html_url: 'https://github.com/microsoft/PowerToys', updated_at: '2024-10-01T00:00:00+00:00', license: 'MIT', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 14427919, full_name: 'obsproject/obs-studio', name: 'OBS Studio', description: 'Free and open source software for live streaming and screen recording', owner: 'obsproject', repo: 'obs-studio', avatar_url: 'https://avatars.githubusercontent.com/u/7725691', stars: 60000, forks: 8200, language: 'C', topics: ['streaming', 'recording', 'linux'], platforms: ['Windows', 'macOS', 'Linux'], latest_version: '30.0.2', latest_release_date: null, html_url: 'https://github.com/obsproject/obs-studio', updated_at: '2024-10-01T00:00:00+00:00', license: 'GPL-2.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 67039432, full_name: 'Eugeny/tabby', name: 'Tabby', description: 'A terminal for a more modern age (formerly Terminus)', owner: 'Eugeny', repo: 'tabby', avatar_url: 'https://avatars.githubusercontent.com/u/161899', stars: 59000, forks: 3400, language: 'TypeScript', topics: ['electron', 'terminal', 'ssh'], platforms: ['Windows', 'macOS', 'Linux'], latest_version: 'v1.0.213', latest_release_date: null, html_url: 'https://github.com/Eugeny/tabby', updated_at: '2024-10-01T00:00:00+00:00', license: 'MIT', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 77000001, full_name: 'localsend/localsend', name: 'LocalSend', description: 'Share files to nearby devices cross-platform', owner: 'localsend', repo: 'localsend', avatar_url: 'https://avatars.githubusercontent.com/u/101477003', stars: 50000, forks: 2500, language: 'Dart', topics: ['flutter', 'android', 'ios', 'windows', 'macos', 'linux'], platforms: ['Android', 'iOS', 'Windows', 'macOS', 'Linux'], latest_version: 'v1.15.4', latest_release_date: null, html_url: 'https://github.com/localsend/localsend', updated_at: '2024-10-01T00:00:00+00:00', license: 'Apache-2.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 77000003, full_name: 'immich-app/immich', name: 'Immich', description: 'High performance self-hosted photo and video management solution', owner: 'immich-app', repo: 'immich', avatar_url: 'https://avatars.githubusercontent.com/u/85899756', stars: 48000, forks: 2300, language: 'TypeScript', topics: ['android', 'ios', 'flutter', 'photos'], platforms: ['Android', 'iOS'], latest_version: 'v1.119.0', latest_release_date: null, html_url: 'https://github.com/immich-app/immich', updated_at: '2024-10-01T00:00:00+00:00', license: 'AGPL-3.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 41656041, full_name: 'marktext/marktext', name: 'Mark Text', description: 'A simple and elegant markdown editor', owner: 'marktext', repo: 'marktext', avatar_url: 'https://avatars.githubusercontent.com/u/29987302', stars: 46000, forks: 3300, language: 'JavaScript', topics: ['electron', 'markdown', 'editor'], platforms: ['Windows', 'macOS', 'Linux'], latest_version: 'v0.17.1', latest_release_date: null, html_url: 'https://github.com/marktext/marktext', updated_at: '2024-08-01T00:00:00+00:00', license: 'MIT', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 43796420, full_name: 'lyswhut/lx-music-desktop', name: 'LX Music Desktop', description: 'A music software based on Electron', owner: 'lyswhut', repo: 'lx-music-desktop', avatar_url: 'https://avatars.githubusercontent.com/u/26362970', stars: 41000, forks: 5800, language: 'JavaScript', topics: ['electron', 'music'], platforms: ['Windows', 'macOS', 'Linux'], latest_version: 'v2.9.3', latest_release_date: null, html_url: 'https://github.com/lyswhut/lx-music-desktop', updated_at: '2024-10-01T00:00:00+00:00', license: 'Apache-2.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 55000002, full_name: 'files-community/Files', name: 'Files App', description: 'Building the best file manager for Windows', owner: 'files-community', repo: 'Files', avatar_url: 'https://avatars.githubusercontent.com/u/57088781', stars: 35000, forks: 2200, language: 'C#', topics: ['windows', 'file-manager'], platforms: ['Windows'], latest_version: 'v3.7.3', latest_release_date: null, html_url: 'https://github.com/files-community/Files', updated_at: '2024-10-01T00:00:00+00:00', license: 'MIT', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 55000001, full_name: 'ShareX/ShareX', name: 'ShareX', description: 'Screen capture, file sharing and productivity tool', owner: 'ShareX', repo: 'ShareX', avatar_url: 'https://avatars.githubusercontent.com/u/2849841', stars: 30000, forks: 3300, language: 'C#', topics: ['windows', 'screen-capture'], platforms: ['Windows'], latest_version: 'v16.1.0', latest_release_date: null, html_url: 'https://github.com/ShareX/ShareX', updated_at: '2024-10-01T00:00:00+00:00', license: 'GPL-3.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 14053048, full_name: 'TeamNewPipe/NewPipe', name: 'NewPipe', description: 'A libre lightweight streaming frontend for Android', owner: 'TeamNewPipe', repo: 'NewPipe', avatar_url: 'https://avatars.githubusercontent.com/u/18327190', stars: 29000, forks: 2900, language: 'Java', topics: ['android', 'youtube', 'streaming'], platforms: ['Android'], latest_version: 'v0.27.2', latest_release_date: null, html_url: 'https://github.com/TeamNewPipe/NewPipe', updated_at: '2024-10-20T00:00:00+00:00', license: 'GPL-3.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 45600329, full_name: 'signalapp/Signal-Android', name: 'Signal Android', description: 'A private messenger for Android', owner: 'signalapp', repo: 'Signal-Android', avatar_url: 'https://avatars.githubusercontent.com/u/702459', stars: 26000, forks: 6200, language: 'Java', topics: ['android', 'privacy', 'messaging'], platforms: ['Android'], latest_version: 'v7.6.3', latest_release_date: null, html_url: 'https://github.com/signalapp/Signal-Android', updated_at: '2024-11-01T00:00:00+00:00', license: 'GPL-3.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 66000002, full_name: 'rxhanson/Rectangle', name: 'Rectangle', description: 'Move and resize windows in macOS', owner: 'rxhanson', repo: 'Rectangle', avatar_url: 'https://avatars.githubusercontent.com/u/13171434', stars: 25000, forks: 800, language: 'Swift', topics: ['macos', 'window-manager'], platforms: ['macOS'], latest_version: 'v0.83', latest_release_date: null, html_url: 'https://github.com/rxhanson/Rectangle', updated_at: '2024-10-01T00:00:00+00:00', license: 'MIT', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 100480262, full_name: 'Molunerfinn/PicGo', name: 'PicGo', description: 'A tool for quickly uploading pictures', owner: 'Molunerfinn', repo: 'PicGo', avatar_url: 'https://avatars.githubusercontent.com/u/8536949', stars: 24000, forks: 1900, language: 'TypeScript', topics: ['electron', 'image-upload'], platforms: ['Windows', 'macOS', 'Linux'], latest_version: 'v2.4.0', latest_release_date: null, html_url: 'https://github.com/Molunerfinn/PicGo', updated_at: '2024-09-01T00:00:00+00:00', license: 'MIT', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 55000005, full_name: 'notepad-plus-plus/notepad-plus-plus', name: 'Notepad++', description: 'A free source code editor and Notepad replacement', owner: 'notepad-plus-plus', repo: 'notepad-plus-plus', avatar_url: 'https://avatars.githubusercontent.com/u/33033', stars: 22000, forks: 4500, language: 'C++', topics: ['windows', 'editor'], platforms: ['Windows'], latest_version: 'v8.7', latest_release_date: null, html_url: 'https://github.com/notepad-plus-plus/notepad-plus-plus', updated_at: '2024-10-01T00:00:00+00:00', license: 'GPL-2.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 66000001, full_name: 'gnachman/iTerm2', name: 'iTerm2', description: 'iTerm2 is a replacement for Terminal and the successor to iTerm', owner: 'gnachman', repo: 'iTerm2', avatar_url: 'https://avatars.githubusercontent.com/u/2462', stars: 15000, forks: 1200, language: 'Objective-C', topics: ['macos', 'terminal'], platforms: ['macOS'], latest_version: '3.5.6', latest_release_date: null, html_url: 'https://github.com/gnachman/iTerm2', updated_at: '2024-10-01T00:00:00+00:00', license: 'GPL-2.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 77000002, full_name: 'ente-io/ente', name: 'Ente Photos', description: 'End-to-End Encrypted alternative to Google Photos', owner: 'ente-io', repo: 'ente', avatar_url: 'https://avatars.githubusercontent.com/u/79704774', stars: 15000, forks: 1000, language: 'Dart', topics: ['flutter', 'android', 'ios', 'photos', 'privacy'], platforms: ['Android', 'iOS', 'Windows', 'macOS', 'Linux'], latest_version: 'v0.9.50', latest_release_date: null, html_url: 'https://github.com/ente-io/ente', updated_at: '2024-10-01T00:00:00+00:00', license: 'AGPL-3.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 55000004, full_name: 'glzr-io/glazewm', name: 'GlazeWM', description: 'Tiling window manager for Windows inspired by i3', owner: 'glzr-io', repo: 'glazewm', avatar_url: 'https://avatars.githubusercontent.com/u/34004402', stars: 12900, forks: 280, language: 'Rust', topics: ['windows', 'tiling', 'window-manager'], platforms: ['Windows'], latest_version: 'v3.7.0', latest_release_date: null, html_url: 'https://github.com/glzr-io/glazewm', updated_at: '2024-10-01T00:00:00+00:00', license: 'GPL-2.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 55000006, full_name: 'marticliment/UniGetUI', name: 'UniGetUI', description: 'GUI for Windows Package Managers', owner: 'marticliment', repo: 'UniGetUI', avatar_url: 'https://avatars.githubusercontent.com/u/53390', stars: 12800, forks: 560, language: 'Python', topics: ['windows', 'package-manager'], platforms: ['Windows'], latest_version: 'v3.1.1', latest_release_date: null, html_url: 'https://github.com/marticliment/UniGetUI', updated_at: '2024-10-01T00:00:00+00:00', license: 'LGPL-2.1', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 66000004, full_name: 'p0deje/Maccy', name: 'Maccy', description: 'macOS clipboard manager', owner: 'p0deje', repo: 'Maccy', avatar_url: 'https://avatars.githubusercontent.com/u/9049178', stars: 12000, forks: 380, language: 'Swift', topics: ['macos', 'clipboard'], platforms: ['macOS'], latest_version: 'v2.1.1', latest_release_date: null, html_url: 'https://github.com/p0deje/Maccy', updated_at: '2024-10-01T00:00:00+00:00', license: 'MIT', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 77000004, full_name: 'xournalpp/xournalpp', name: 'Xournal++', description: 'Handwriting note-taking software', owner: 'xournalpp', repo: 'xournalpp', avatar_url: 'https://avatars.githubusercontent.com/u/18348382', stars: 11200, forks: 900, language: 'C++', topics: ['linux', 'windows', 'macos', 'notes'], platforms: ['Windows', 'macOS', 'Linux'], latest_version: 'v2.2.3', latest_release_date: null, html_url: 'https://github.com/xournalpp/xournalpp', updated_at: '2024-10-01T00:00:00+00:00', license: 'GPL-2.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 66000003, full_name: 'lwouis/alt-tab-macos', name: 'AltTab', description: 'Windows alt-tab on macOS', owner: 'lwouis', repo: 'alt-tab-macos', avatar_url: 'https://avatars.githubusercontent.com/u/24397268', stars: 11100, forks: 350, language: 'Swift', topics: ['macos', 'productivity'], platforms: ['macOS'], latest_version: 'v6.71.0', latest_release_date: null, html_url: 'https://github.com/lwouis/alt-tab-macos', updated_at: '2024-10-01T00:00:00+00:00', license: 'GPL-3.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 12345678, full_name: 'nickg/clipboardmanager', name: 'Clipboard Manager', description: 'Cross-platform clipboard manager', owner: 'nickg', repo: 'clipboardmanager', avatar_url: 'https://avatars.githubusercontent.com/u/4632813', stars: 9800, forks: 560, language: 'TypeScript', topics: ['electron', 'clipboard', 'productivity'], platforms: ['Windows', 'macOS', 'Linux'], latest_version: 'v3.2.1', latest_release_date: null, html_url: 'https://github.com/nickg/clipboardmanager', updated_at: '2024-10-01T00:00:00+00:00', license: 'MIT', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 23699231, full_name: 'k9mail/k-9', name: 'K-9 Mail', description: 'Full-featured email client for Android', owner: 'k9mail', repo: 'k-9', avatar_url: 'https://avatars.githubusercontent.com/u/496457', stars: 9800, forks: 2500, language: 'Kotlin', topics: ['android', 'email'], platforms: ['Android'], latest_version: '6.801', latest_release_date: null, html_url: 'https://github.com/k9mail/k-9', updated_at: '2024-10-15T00:00:00+00:00', license: 'Apache-2.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 202613459, full_name: 'organicmaps/organicmaps', name: 'Organic Maps', description: 'Offline Hike, Bike, Trails and Navigation App', owner: 'organicmaps', repo: 'organicmaps', avatar_url: 'https://avatars.githubusercontent.com/u/84673629', stars: 9600, forks: 1100, language: 'C++', topics: ['android', 'ios', 'maps', 'offline'], platforms: ['Android', 'iOS'], latest_version: '2024.10.23', latest_release_date: null, html_url: 'https://github.com/organicmaps/organicmaps', updated_at: '2024-10-23T00:00:00+00:00', license: 'Apache-2.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 93814880, full_name: 'beemdevelopment/Aegis', name: 'Aegis Authenticator', description: 'Free, secure and open source 2FA app for Android', owner: 'beemdevelopment', repo: 'Aegis', avatar_url: 'https://avatars.githubusercontent.com/u/27832341', stars: 9400, forks: 400, language: 'Java', topics: ['android', '2fa', 'authenticator'], platforms: ['Android'], latest_version: 'v3.1', latest_release_date: null, html_url: 'https://github.com/beemdevelopment/Aegis', updated_at: '2024-09-15T00:00:00+00:00', license: 'GPL-3.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 45678912, full_name: 'ankidroid/Anki-Android', name: 'AnkiDroid', description: 'AnkiDroid: Anki flashcards on Android', owner: 'ankidroid', repo: 'Anki-Android', avatar_url: 'https://avatars.githubusercontent.com/u/109004', stars: 8600, forks: 2900, language: 'Kotlin', topics: ['android', 'flashcards', 'education'], platforms: ['Android'], latest_version: '2.18.0', latest_release_date: null, html_url: 'https://github.com/ankidroid/Anki-Android', updated_at: '2024-10-10T00:00:00+00:00', license: 'GPL-3.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 26999801, full_name: 'AntennaPod/AntennaPod', name: 'AntennaPod', description: 'The Easy-to-Use Podcast Manager for Android', owner: 'AntennaPod', repo: 'AntennaPod', avatar_url: 'https://avatars.githubusercontent.com/u/3526856', stars: 6200, forks: 1500, language: 'Java', topics: ['android', 'podcast'], platforms: ['Android'], latest_version: '3.4.0', latest_release_date: null, html_url: 'https://github.com/AntennaPod/AntennaPod', updated_at: '2024-10-01T00:00:00+00:00', license: 'MIT', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 56789012, full_name: 'fast4x/RiMusic', name: 'RiMusic', description: 'Multilingual Android music streaming app from YouTube Music', owner: 'fast4x', repo: 'RiMusic', avatar_url: 'https://avatars.githubusercontent.com/u/133229833', stars: 5200, forks: 320, language: 'Kotlin', topics: ['android', 'music', 'youtube'], platforms: ['Android'], latest_version: 'v0.6.56.1', latest_release_date: null, html_url: 'https://github.com/fast4x/RiMusic', updated_at: '2024-10-01T00:00:00+00:00', license: 'MIT', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 77000005, full_name: 'nickg/kdeconnect', name: 'KDE Connect', description: 'Integrate your phone with your desktop', owner: 'nickg', repo: 'kdeconnect', avatar_url: 'https://avatars.githubusercontent.com/u/1161421', stars: 4200, forks: 900, language: 'C++', topics: ['android', 'linux', 'macos', 'windows'], platforms: ['Android', 'Windows', 'macOS', 'Linux'], latest_version: 'v24.08.2', latest_release_date: null, html_url: 'https://github.com/nickg/kdeconnect', updated_at: '2024-10-01T00:00:00+00:00', license: 'GPL-2.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 91610579, full_name: 'nextcloud/android', name: 'Nextcloud Android', description: 'Nextcloud Android app', owner: 'nextcloud', repo: 'android', avatar_url: 'https://avatars.githubusercontent.com/u/19211038', stars: 4100, forks: 1700, language: 'Java', topics: ['android', 'nextcloud'], platforms: ['Android'], latest_version: '3.30.0', latest_release_date: null, html_url: 'https://github.com/nextcloud/android', updated_at: '2024-10-15T00:00:00+00:00', license: 'GPL-2.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 76543210, full_name: 'tasks/tasks', name: 'Tasks.org', description: 'Open-source To-Do Lists & Reminders', owner: 'tasks', repo: 'tasks', avatar_url: 'https://avatars.githubusercontent.com/u/19219024', stars: 3900, forks: 560, language: 'Kotlin', topics: ['android', 'todo', 'tasks'], platforms: ['Android'], latest_version: '13.10', latest_release_date: null, html_url: 'https://github.com/tasks/tasks', updated_at: '2024-10-01T00:00:00+00:00', license: 'GPL-3.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 23458901, full_name: 'VREMSoftwareDevelopment/WiFiAnalyzer', name: 'WiFiAnalyzer', description: 'Android WiFi network analyzer', owner: 'VREMSoftwareDevelopment', repo: 'WiFiAnalyzer', avatar_url: 'https://avatars.githubusercontent.com/u/17549578', stars: 3700, forks: 890, language: 'Kotlin', topics: ['android', 'wifi', 'network'], platforms: ['Android'], latest_version: 'v3.1.4', latest_release_date: null, html_url: 'https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer', updated_at: '2024-09-01T00:00:00+00:00', license: 'GPL-3.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 125811503, full_name: 'mozilla-mobile/firefox-ios', name: 'Firefox for iOS', description: 'Firefox for iOS', owner: 'mozilla-mobile', repo: 'firefox-ios', avatar_url: 'https://avatars.githubusercontent.com/u/11824804', stars: 3700, forks: 1000, language: 'Swift', topics: ['ios', 'browser', 'firefox'], platforms: ['iOS'], latest_version: 'v130.0', latest_release_date: null, html_url: 'https://github.com/mozilla-mobile/firefox-ios', updated_at: '2024-10-01T00:00:00+00:00', license: 'MPL-2.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 47847117, full_name: 'M66B/FairEmail', name: 'FairEmail', description: 'Privacy-oriented email app for Android', owner: 'M66B', repo: 'FairEmail', avatar_url: 'https://avatars.githubusercontent.com/u/8466984', stars: 3100, forks: 350, language: 'Java', topics: ['android', 'email', 'privacy'], platforms: ['Android'], latest_version: '1.2228', latest_release_date: null, html_url: 'https://github.com/M66B/FairEmail', updated_at: '2024-10-20T00:00:00+00:00', license: 'GPL-3.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
  { id: 34567890, full_name: 'FossifyOrg/Gallery', name: 'Fossify Gallery', description: 'A premium app for managing and editing your photos and videos', owner: 'FossifyOrg', repo: 'Gallery', avatar_url: 'https://avatars.githubusercontent.com/u/156048654', stars: 2800, forks: 410, language: 'Kotlin', topics: ['android', 'gallery', 'photos'], platforms: ['Android'], latest_version: 'v1.1.4', latest_release_date: null, html_url: 'https://github.com/FossifyOrg/Gallery', updated_at: '2024-09-15T00:00:00+00:00', license: 'GPL-3.0', archived: false, open_issues_count: 0, total_downloads: 0, has_installable_assets: true },
];

/** 本地关键词搜索，匹配 name/repo/full_name/description/owner/topics */
export function searchLocalCatalog(keyword: string): AppItem[] {
  const k = keyword.trim().toLowerCase();
  if (!k) return [];
  return LOCAL_CATALOG.filter((r) =>
    r.name?.toLowerCase().includes(k) ||
    r.repo?.toLowerCase().includes(k) ||
    r.full_name?.toLowerCase().includes(k) ||
    r.description?.toLowerCase().includes(k) ||
    r.owner?.toLowerCase().includes(k) ||
    r.topics?.some((t) => t.toLowerCase().includes(k)) ||
    r.platforms?.some((p) => p.toLowerCase().includes(k))
  );
}

/** 按平台过滤本地目录 */
export function filterByPlatform(platform: string | null): AppItem[] {
  if (!platform) return LOCAL_CATALOG;
  return LOCAL_CATALOG.filter((r) => r.platforms?.includes(platform));
}

/** 按 topic 过滤本地目录 */
export function filterByTopic(topic: string | null): AppItem[] {
  if (!topic) return LOCAL_CATALOG;
  return LOCAL_CATALOG.filter((r) => r.topics?.includes(topic));
}
